### ISSUE TITLE
Can we do work on other aspects of COVID19?

### ISSUE THREAD

**Issue by iloveleejunghyun** [SJSUSpring2020-CMPE272/COVID-19-on-the-Market#2]
Hello, team2 members. We don't have ideas on the project, can we do work on other aspects of COVID19? We'll avoid the same ideas of your project and let you know before we make the decision.

**Comment by rhong5** [comment]
The professor said it's fine for us to both work on COVID19 topics. Just so you know, we are working on the effect on the Economy (such as stock market, and unemployment.)
